# -*- coding: utf-8 -*-
"""EXP1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W0IM5ZvI3cn_dUh-enD7pDBxfimfnCJj
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import skew, kurtosis

data = pd.read_csv("exp1_bmi.csv")

data

mean_values = data[['Height', 'Weight', 'bmi', 'Age']].mean()

mean_values

median_values = data[['Height', 'Weight', 'bmi', 'Age']].median()

median_values

mode_values = data[['Height', 'Weight', 'bmi', 'Age']].median()

mode_values

variance_values = data[['Height', 'Weight', 'bmi', 'Age']].var()

variance_values

standard_deviation_values = data[['Height', 'Weight', 'bmi', 'Age']].std()

standard_deviation_values

min_values = data[['Height', 'Weight', 'bmi', 'Age']].min()

min_values

max_values = data[['Height', 'Weight', 'bmi', 'Age']].max()

max_values

range = max_values - min_values

range

Q1 = data[['Height', 'Weight', 'bmi', 'Age']].quantile(0.25)
Q3 = data[['Height', 'Weight', 'bmi', 'Age']].quantile(0.75)
IQR = Q3 - Q1

IQR

data.boxplot()

plt.title('Boxplot of Data')
plt.xlabel('Variables')
plt.ylabel('Values')

plt.show()

sns.boxplot(x=data['Height'])

plt.title('Boxplot of Height')
plt.ylabel('Height')

plt.show()

sns.boxplot(x=data['Weight'])

plt.title('Boxplot of Weight')
plt.ylabel('Weight')

plt.show()

sns.boxplot(x=data['bmi'])

plt.title('Boxplot of bmi')
plt.ylabel('bmi')

plt.show()

sns.boxplot(x=data['Age'])

plt.title('Boxplot of Age')
plt.ylabel('Age')

plt.show()

data["Height"].describe()

data["Weight"].describe()

data["Age"].describe()

data["bmi"].describe()

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='Gender', data=data)

plt.title('Count of Gender')
plt.xlabel('Gender')
plt.ylabel('Count')

plt.show()

skewness = skew(data['Age'])


kurt = kurtosis(data['Age'])

print("Skewness:", skewness)
print("Kurtosis:", kurt)

skewness = skew(data['Height'])


kurt = kurtosis(data['Height'])

print("Skewness:", skewness)
print("Kurtosis:", kurt)

skewness = skew(data['Weight'])


kurt = kurtosis(data['Weight'])

print("Skewness:", skewness)
print("Kurtosis:", kurt)

skewness = skew(data['bmi'])


kurt = kurtosis(data['bmi'])

print("Skewness:", skewness)
print("Kurtosis:", kurt)

gender_counts = data['Gender'].value_counts()
print(gender_counts)

