# -*- coding: utf-8 -*-
"""Inferential Statistic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8Zh_uE-peJF76yr2d-9EE2DJa1Az3te
"""

import numpy as np
import pandas as pd
from scipy import stats

bata_RelianceDataMart=pd.read_excel('exp3_RelianceDataMart.xlsx')
bata_RelianceDataMart

print(bata_RelianceDataMart.mean())

bata_RelianceDataMart.describe()

one_sample_result=stats.ttest_1samp(bata_RelianceDataMart,24.446)
print(one_sample_result)

bata_Pre_Post_Score=pd.read_csv('exp3_Pre_Post_Score.csv')
bata_Pre_Post_Score

two_sample_result=stats.ttest_rel (bata_Pre_Post_Score ["Pre_Score"], bata_Pre_Post_Score ["Post_Score"])

two_sample_result

bata_Crocin_Data_ST=pd.read_excel('exp3_Crocin_Data_ST.xlsx')
bata_Crocin_Data_ST

two_sample_result1=stats.ttest_rel (bata_Crocin_Data_ST ["Before_Crocin"], bata_Crocin_Data_ST ["After_Crocin"])

two_sample_result1

# One sample t-test has been done on the reliance data mart dataset and it has been found that
# difference exists between the rice bag population mean and rice bag sample mean. Two sample
# paired t-test has been done on the prescore-post score dataset and Crocin dataset. In the
# prescore-post score dataset difference exists between the mean pre-score before studying the
# module and mean prescore after studying the module. In the crocin dataset it is found that
# temperature difference exists before and after having the crocin tablet.